# Site Info
title:              "ChrBecker"
description:        "My academic site"
author_name:        "Christoph Becker"
logo_url:           /assets/selfie_real_voronoi_outline.jpg
logo_url_hover:     /assets/selfie_mix_1.jpg

# Site Settings
url:                https://christovis.github.io/
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
collections:
  research:
    output: true
    permalink: /research/:name
  projects:
    output: true
    permalink: /projects/:name
  talks:
    output: true
    permalink: /talks/:name
  blog:
    output: true
    permalink: /blog/:name

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      type:         "research"
    values:
      layout:       "research-post"
  -
    scope:
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      type:         "talks"
    values:
      layout:       "post"
  -
    scope:
      type:         "blog"
    values:
      layout:       "post"
